services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: matra-sre:local
    volumes:
      - ./data:/data

  test:
    build:
      context: .
      dockerfile: Dockerfile
    image: matra-sre:local
    entrypoint: ["sh", "-lc"]
    command: "uv run main.py --help"
